<?php if ($block->canShowInCategory()) : ?>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0],
          locale = '<?php echo $block->getButtonLocale() ?>',
          appId = '<?php echo $block->getFacebookAppId() ?>';
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/"+ locale +"/sdk.js#xfbml=1&version=v2.5&appId=" + appId;
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<?php endif ?>
