<?php $config = $block->getLikeButtonConfig(); ?>
<?php if ($config["enabled"]) : ?>
    <div style="margin-top:10px;">
        <div id="fb-root"></div>
        <?php if ($config["layout"] === "custom") : ?>
          <p class="fbl-custom">
            <a class="like"
                data-url="<?php echo $block->getProductUrl();?>"
                title="<?php echo __('Like product on Facebook')?>">
            </a>
          </p>
        <?php else : ?>
          <div class="fb-like"
              data-href="<?php echo $block->getProductUrl() ?>"
              data-layout="<?php echo $config['layout'] ?>"
              data-action="<?php echo $config['action'] ?>"
              data-colorscheme="<?php echo $config['colorscheme'] ?>"
              data-share="<?php echo $config['share'] ?>"
              data-show-faces="<?php echo $config['show_faces'] ?>">
          </div>
        <?php endif; ?>
    </div>
    <script type="text/javascript">
        require([
            'jquery',
            'fbl'
        ], function ($, fbl) {
            var locale = '<?php echo $block->getButtonLocale() ?>';
            var appId = '<?php echo $block->getFacebookAppId() ?>';
            fbl.init(locale, appId);
        });
    </script>
<?php endif ?>
